plugins:
  wizard_redirect_exclude_paths:
    client: true
    type: list
    default: 'admin'
    choices:
      - admin
      - privacy
  wizard_recognised_image_upload_formats:
    client: true
    default: "jpg|jpeg|png|gif"
    refresh: true
    type: list
    list_type: compact
  wizard_national_flags_label_cue:
    client: true
    default: "National"
